# Generated by Django 5.1.6 on 2025-02-14 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorsnote', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorsnote',
            name='is_booked',
            field=models.BooleanField(default=True),
        ),
    ]
