# Generated by Django 5.1.6 on 2025-02-14 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctorsnote', '0004_alter_doctorsnote_booking_delete_bookdoctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorsnote',
            name='is_booked',
        ),
    ]
