# Generated by Django 5.1.6 on 2025-02-14 16:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctorsnote', '0005_remove_doctorsnote_is_booked'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionableTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task_type', models.CharField(choices=[('checklist', 'One-time Task'), ('plan', 'Scheduled Task')], max_length=10)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('reminder_status', models.CharField(choices=[('scheduled', 'Scheduled'), ('sent', 'Sent'), ('acknowledged', 'Acknowledged')], default='scheduled', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scheduled_date', models.DateTimeField(blank=True, null=True)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('repeat_count', models.IntegerField(default=1)),
                ('current_repetition', models.IntegerField(default=0)),
                ('last_reminder_sent', models.DateTimeField(blank=True, null=True)),
                ('next_reminder_date', models.DateTimeField(blank=True, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_tasks', to=settings.AUTH_USER_MODEL)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctorsnote.doctorsnote')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['scheduled_date', 'created_at'],
            },
        ),
    ]
