# Generated by Django 5.1.6 on 2025-02-13 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('doctor', 'doctor'), ('patient', 'patient')], null=True),
        ),
    ]
