# Generated by Django 5.1.6 on 2025-02-13 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_address_remove_user_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
